name: ruijindongning
on:
  workflow_dispatch:

  schedule:
    - cron: '53 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruijindongning
        env:
          mqcpi3: ${{ secrets.mqcpi3 }}
        run: |
          printf '%s' "$mqcpi3" | jq -r .kyrgz0894 | /bin/bash
          printf '%s' "$qky0" | jq -r .yxzuj22316 | /bin/bash
          printf '%s' "$ase1212" | jq -r .xu74 | /bin/bash
          echo $cyi2 | jq -r .kp7 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LzVyk1KV
          path: "*.zip"
          retention-days: 1
